# Numpy Tutorial

In [ ]:
# Install numpy using conda
!conda install -c anaconda numpy
# Or using pip
!pip install numpy

In [ ]:
import numpy as np

## Creating arrays

In [ ]:
# 1D arrays

# creating python list
list1 = [3,2,5]
arr1 = np.array(list1, dtype=np.int16)
print(arr1)

# or
arr1 = np.array([3,2,5])
print(arr1)

# creating arrays of complex numbers
arr_complex = np.array([1,2,4], dtype= complex)
print(arr_complex)

[3 2 5]
[3 2 5]
[1.+0.j 2.+0.j 4.+0.j]


In [ ]:
# multi-dimensional array
list_m = [[1,2,3], [4,5,6], [7,8,9]]
arr_m = np.array(list_m, dtype=np.int16)
print(arr_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# creating an array of all zeros
arr_0 = np.zeros((2,2))
print(arr_0)

# creating an array of all ones
arr_1 = np.ones((1,4))
print(arr_1)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]]


In [ ]:
# creating a constant array
arr_c = np.full((2,2), 7)
print(arr_c)

# or using np.ones
arr_c = np.ones((2,2)) * 7
print(arr_c)
print(arr_c.dtype)

[[7 7]
 [7 7]]
[[7. 7.]
 [7. 7.]]
float64


In [ ]:
# creating an array with start value, end value and number of values
arr_L = np.linspace(0, 5, 7)
print(arr_L)
print(arr_L.dtype)

[0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]
float64


In [ ]:
# creating an array with start value, end value
# and number of values (dtype int)
arr_a = np.arange(1, 10, 2)
print(arr_a)
print(arr_a.dtype)

[1 3 5 7 9]
int32


In [ ]:
# an array filled with random values
# np.random.seed(32)
arr_r = np.random.random((2,2))
print(arr_r)

[[0.85888927 0.37271115]
 [0.55512878 0.95565655]]


In [ ]:
# an array filled with random integers
arr_1 = np.random.randint(10,100,7) # low (inclusive), high (exclusive), and number of values
print(arr_1)

[20 94 60 67 79 48 87]


In [ ]:
# an array filled with random values following the normal distribution.
arr_n = np.random.randn(10)
print(arr_n)

[-1.62830331  0.96699774  0.05311559  0.28971293  0.06244434 -1.09812873
  0.13053306 -0.18533706 -1.34073473 -0.32401968]


In [ ]:
# create a 2x2 identity matrix
arr_I = np.eye(2)
print(arr_I)

[[1. 0.]
 [0. 1.]]


## Creating arrays from existing data

In [ ]:
# converting list to ndarray
x = [1,2,3]
a = np.asarray(x)
print(a)

# ndarray from tuple
y = (1,2,3)
b = np.asarray(y)
print(b)

# ndarray from a list of tuples
z = [(1,2,3), (4,5)]
c = np.asarray(z)
print(c)


[1 2 3]
[1 2 3]
[(1, 2, 3) (4, 5)]


## Array attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)    # returns the total number of elements in an array.
print(arr.ndim)    # returns the number of array dimensions. 
print(type(arr))   # to check the variable type.
print(arr.dtype)   # to check the data type or numeric type of the array.

# resizing
arr_1 = arr.reshape(3,2)
print(arr_1.shape)

arr_2 = arr.reshape(1,-1)
print(arr_2.shape)

# transpose
print(arr)
print(arr.T)

(2, 3)
6
2
<class 'numpy.ndarray'>
int32
(3, 2)
(1, 6)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Indexing and slicing

In [ ]:
arr = np.arange(10)
print(arr)

print(arr[7])
# or
print(arr[-3])

print(arr[:5])
print(arr[:-4])

print(arr[9:])
# or
print(arr[-1:])

print(arr[-4:-1])

# slicing with a step
print(arr[2:-1:2])

# omitted indices
print(arr[::2])
print(arr[::-1])    # reverse order

[0 1 2 3 4 5 6 7 8 9]
7
7
[0 1 2 3 4]
[0 1 2 3 4 5]
[9]
[9]
[6 7 8]
[2 4 6 8]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# multi-dimensional arrays
arr = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(arr)

# slicing first row
print(arr[0:1])

# slicing last 2 rows
print(arr[-2:])

# slicing 3 rows and first column
print(arr[0:3,0:1])
# or
print(arr[:3,:1])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2 3]]
[[3 4 5]
 [4 5 6]]
[[1]
 [3]
 [4]]
[[1]
 [3]
 [4]]


## Basic math operations

In [ ]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([2, 4, 6, 8])
# Add values
print(arr_1 + arr_2)
# or
np.add(arr_1 ,arr_2)

[ 3  6  9 12]


array([ 3,  6,  9, 12])

In [ ]:
# Subtract
print(arr_1 - arr_2)
# or
np.subtract(arr_1 ,arr_2)

[-1 -2 -3 -4]


array([-1, -2, -3, -4])

In [ ]:
# Multiply
print(arr_1 * arr_2)
# or
np.multiply(arr_1 ,arr_2)

[ 2  8 18 32]


array([ 2,  8, 18, 32])

In [ ]:
# Divide
print(arr_1 / arr_2)
# or
np.divide(arr_1,arr_2)

[0.5 0.5 0.5 0.5]


array([0.5, 0.5, 0.5, 0.5])

In [ ]:
# Random 2 by 3 digit 2D array between 0 to 100
arr_3 =np.random.randint(100, size=(2, 3))
print(arr_3)
print()

# Sum of values in array
print(arr_1.sum())
print()

# Sum columns
print(arr_3.sum(axis=0))
print()

# Cumulative sum of rows
print(arr_3.cumsum(axis=1))

[[60 78 92]
 [89 62 82]]

10

[149 140 174]

[[ 60 138 230]
 [ 89 151 233]]


In [ ]:
# Min and max values from array
arr=np.array([[62, 96, 50],
       [87, 26, 42]])
print(arr)

# Min of each row
print(arr.min(axis=1))

# Max of each column
print(arr.max(axis=0))

# Absolute value of every element
print(np.absolute([-1,-2]))


[[62 96 50]
 [87 26 42]]
[50 26]
[87 96 50]
[1 2]


## Linear Algebra

In [ ]:
a = np.random.random((2,3))
b = np.random.random((3,4))
print(a)
print(b)
print()

c = np.dot(a,b)
print(c.shape)

[[0.1565324  0.8933882  0.01109693]
 [0.76347618 0.77305726 0.57279222]]
[[0.98148999 0.00867733 0.14020093 0.21361893]
 [0.46732004 0.80811245 0.60119557 0.41356072]
 [0.36902067 0.68852574 0.62160303 0.78923097]]

(2, 4)


In [ ]:
from numpy import linalg
x = np.random.randint(0, 10, 3)
print(x)

print(linalg.norm(x))  # second-order, also same as vector length 

A = np.random.random((2,3))
print(A.shape)

b = np.dot(A,x)
print(b)
print(b.shape)


[9 4 3]
10.295630140987
(2, 3)
[ 8.15537134 10.24858816]
(2,)


In [ ]:
# Solve a linear system Av = b
A = np.random.random((2,2))
v = linalg.solve(A,b)    # A should be invertible and square
print(v)

[ 9.0777615 32.5729419]


In [ ]:
eigvals, eigvecs = linalg.eig(A)
print(eigvals)
print(eigvecs)

[0.84639773 0.30332913]
[[ 0.99768419 -0.02723847]
 [ 0.06801653  0.99962896]]
